sql:
    default: 'postgre'
    postgre:
        lib: 'psycopg2'
        args: []
        kwargs:
            host: "localhost"
            port: 5432
            database: "cw_local"
            user: "postgres"
            password: "postgres"

fhirbase:
    host: "localhost"
    port: 5432
    database: "fhirbase"
    user: "postgres"

filesystem:
    mapping: '../../fhir-mapping'

graphql:
    server: 'https://graphql.live.arkhn.org/'
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjanRpdXplNncwMHJqMDk2MmMzNnl4Z3hkIiwiaWF0IjoxNTUzMTg2NTY0fQ.dACqyzzvOkukbpypZCR4_OuPbS8c-DxWyr8zRcsDdMg"
