sql:
    default: 'postgre'
    postgre:
        lib: 'psycopg2'
        args: []
        kwargs:
            host: "localhost"
            port: 5432
            database: "database"
            user: "postgres"
            password: "postgres"
    oracle:
        lib: 'cx_Oracle'
        args: ['user/password@database']
        kwargs: {}


fhirbase:
    host: "localhost"
    port: 5432
    database: "fhirbase"
    user: "postgres"

graphql:
    server: 'https://graphql.live.arkhn.org/'
    token: "<token>"
