sql:
    default: 'postgre'
    postgre:
        lib: 'psycopg2'
        args: []
        kwargs:
            host: "localhost"
            port: 5432
            database: "mimic"
            user: "mimicuser"
            password: "mimicuser"
    oracle:
        lib: 'cx_Oracle'
        args: ['user/password@database']
        kwargs: {}


fhirbase:
    host: "localhost"
    port: 5433
    database: "fhirbase"
    user: "postgres"
    password: "postgres"

graphql:
    server: 'https://graphql.pyrog.staging.arkhn.org/'
    token: "<token>"
