sql:
    default: 'oracle'
    postgre:
        lib: 'psycopg2'
        args: []
        kwargs:
            host: "localhost"
            port: 5432
            database: "cw_local"
            user: "postgres"
            password: "postgres"
    oracle:
        lib: 'cx_Oracle'
        args: ['system/cwprod2@CWPROD']
        kwargs: {}
filesystem:
    mapping: '../fhir-mappings'
graphql:
    server: 'https://graphql.live.arkhn.org/'
